### ISSUE TITLE
Pattern may be out of date?

### ISSUE THREAD

**Issue by LionHackerman** [lguilhermee/EAC-Extractor-Utility#1]
When hitting this line:
` auto size1 = *(uint32_t*)ResolveRelative(PatternScan((uintptr_t)launcherData, "BE ? ? ? ? E9 ? ? ? ? 8B 3D").at(0) + 0xA, 2, 6);`

I get the "invalid vector subscript" error. 

![error](https://github.com/lguilhermee/EAC-Extractor-Utility/assets/58070003/7cb7ddd5-5892-4e43-bcc9-a094c02126fd)

**Comment by lguilhermee** [comment]
On my testing i targeted three games which them worked, but they are not bullet proof, can you send me the file or the link so i can download and check?

**Comment by LionHackerman** [comment]
> On my testing i targeted three games which them worked, but they are not bullet proof, can you send me the file or the link so i can download and check?

https://modules-cdn.eac-prod.on.epicgames.com/modules/dad9113550dd48da80dfe231e9dc69a6/7c58849119044361adced203175f63d0/wow64_win64

**Comment by lguilhermee** [comment]
The issue is because the games which i was targeting had the Launcher module as x64, the one that you provided is x32. I have added the pattern for x32 modules at this: aca07d9e10f4a3c95573fadf471afd640380d549 commit. 

Remember to compile the tool for your specific plataform
